
/*
 * Constants for dispid`s
 *
 * Copyright (C) 2008 Sinitsin Ivan (Etersoft) <ivan@etersoft.ru>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

/*ExcelApplication*/
#define dispid_application_usercontrol                           1210
#define dispid_application_displayalerts                         343
#define dispid_application_windowstate                           396
#define dispid_application_visible                               558
#define dispid_application_workbooks                             572
#define dispid_application_sheets                                485
#define dispid_application_worksheets                            494
#define dispid_application_cells                                 238
#define dispid_application_activesheet                           307
#define dispid_application_version                               392
#define dispid_application_convertformula                        325
#define dispid_application_quit                                  302
#define dispid_application_activecell                            305
#define dispid_application_application                           148
#define dispid_application_enableevents                          1212
#define dispid_application_screenupdating                        382
#define dispid_application_caption                               139
#define dispid_application_activeworkbook                        308
#define dispid_application_range                                 197
#define dispid_application_columns                               241
#define dispid_application_rows                                  258
#define dispid_application_selection                             147
#define dispid_application_creator                               149
#define dispid_application_parent                                150
#define dispid_application_activechart                           183
#define dispid_application_activedialog                          815
#define dispid_application_activemenubar                         758
#define dispid_application_activeprinter                         306
#define dispid_application_activewindow                          759
#define dispid_application_addins                                549
#define dispid_application_assistant                             1438
#define dispid_application_calculate                             279
#define dispid_application_charts                                121
#define dispid_application_commandbars                           1439
#define dispid_application_ddeappreturncode                      332
#define dispid_application_ddeexecute                            333
#define dispid_application_ddeinitiate                           334
#define dispid_application_ddepoke                               335
#define dispid_application_dderequest                            336
#define dispid_application_ddeterminate                          337
#define dispid_application_dialogsheets                          764
#define dispid_application_evaluate                              1
#define dispid_application__evaluate                             -5
#define dispid_application_evaluateexcel4macro                   350
#define dispid_application_intersect                             766
#define dispid_application_menubars                              589
#define dispid_application_modules                               582
#define dispid_application_names                                 442
#define dispid_application_run                                   259
#define dispid_application__run2                                 806
#define dispid_application_sendkeys                              383
#define dispid_application_shortcutmenus                         776
#define dispid_application_thisworkbook                          778
#define dispid_application_toolbars                              552
#define dispid_application_union                                 779
#define dispid_application_windows                               430
#define dispid_application_worksheetfunction                     1440
#define dispid_application_excel4intlmacrosheets                 581
#define dispid_application_excel4macrosheets                     579
#define dispid_application_activatemicrosoftapp                  1095
#define dispid_application_addchartautoformat                    216
#define dispid_application_addcustomlist                         780
#define dispid_application_alertbeforeoverwriting                930
#define dispid_application_altstartuppath                        313
#define dispid_application_asktoupdatelinks                      992
#define dispid_application_enableanimation                       1180
#define dispid_application_autocorrect                           1145
#define dispid_application_build                                 314
#define dispid_application_calculatebeforesave                   315
#define dispid_application_calculation                           316
#define dispid_application_caller                                317
#define dispid_application_canplaysounds                         318
#define dispid_application_canrecordsounds                       319
#define dispid_application_celldraganddrop                       320
#define dispid_application_centimeterstopoints                   1086
#define dispid_application_checkspelling                         505
#define dispid_application_clipboardformats                      321
#define dispid_application_displayclipboardwindow                322
#define dispid_application_colorbuttons                          365
#define dispid_application_commandunderlines                     323
#define dispid_application_constrainnumeric                      324
#define dispid_application_copyobjectswithcells                  991
#define dispid_application_cursor                                1161
#define dispid_application_customlistcount                       787
#define dispid_application_cutcopymode                           330
#define dispid_application_dataentrymode                         331
#define dispid_application_dummy1                                1782
#define dispid_application_dummy2                                1783
#define dispid_application_dummy3                                1784
#define dispid_application_dummy4                                1785
#define dispid_application_dummy5                                1786
#define dispid_application_dummy6                                1787
#define dispid_application_dummy7                                1788
#define dispid_application_dummy8                                1789
#define dispid_application_dummy9                                1790
#define dispid_application_dummy10                               1791
#define dispid_application_dummy11                               1792
#define dispid_application__default                              0
#define dispid_application_defaultfilepath                       1038
#define dispid_application_deletechartautoformat                 217
#define dispid_application_deletecustomlist                      783
#define dispid_application_dialogs                               761
#define dispid_application_displayformulabar                     344
#define dispid_application_displayfullscreen                     1061
#define dispid_application_displaynoteindicator                  345
#define dispid_application_displaycommentindicator               1196
#define dispid_application_displayexcel4menus                    927
#define dispid_application_displayrecentfiles                    926
#define dispid_application_displayscrollbars                     346
#define dispid_application_displaystatusbar                      347
#define dispid_application_doubleclick                           349
#define dispid_application_editdirectlyincell                    929
#define dispid_application_enableautocomplete                    1179
#define dispid_application_enablecancelkey                       1096
#define dispid_application_enablesound                           1197
#define dispid_application_enabletipwizard                       1064
#define dispid_application_fileconverters                        931
#define dispid_application_filesearch                            1200
#define dispid_application_filefind                              1201
#define dispid_application__findfile                             1068
#define dispid_application_fixeddecimal                          351
#define dispid_application_fixeddecimalplaces                    352
#define dispid_application_getcustomlistcontents                 786
#define dispid_application_getcustomlistnum                      785
#define dispid_application_getopenfilename                       1075
#define dispid_application_getsaveasfilename                     1076
#define dispid_application_goto                                  475
#define dispid_application_height                                123
#define dispid_application_help                                  354
#define dispid_application_ignoreremoterequests                  356
#define dispid_application_inchestopoints                        1087
#define dispid_application_inputbox                              357
#define dispid_application_interactive                           361
#define dispid_application_international                         362
#define dispid_application_iteration                             363
#define dispid_application_largebuttons                          364
#define dispid_application_left                                  127
#define dispid_application_librarypath                           366
#define dispid_application_macrooption                           1135
#define dispid_application_maillogoff                            945
#define dispid_application_maillogon                             943
#define dispid_application_mailsession                           942
#define dispid_application_mailsystem                            971
#define dispid_application_mathcoprocessoravailable              367
#define dispid_application_maxchange                             368
#define dispid_application_maxiterations                         369
#define dispid_application_memoryfree                            370
#define dispid_application_memorytotal                           371
#define dispid_application_memoryused                            373882
#define dispid_application_mouseavailable                        373
#define dispid_application_moveafterreturn                       374
#define dispid_application_moveafterreturndirection              1144
#define dispid_application_recentfiles                           1202
#define dispid_application_name                                  110
#define dispid_application_nextletter                            972
#define dispid_application_networktemplatespath                  388
#define dispid_application_odbcerrors                            1203
#define dispid_application_odbctimeout                           1204
#define dispid_application_oncalculate                           625
#define dispid_application_ondata                                629
#define dispid_application_ondoubleclick                         628
#define dispid_application_onentry                               627
#define dispid_application_onkey                                 626
#define dispid_application_onrepeat                              769
#define dispid_application_onsheetactivate                       1031
#define dispid_application_onsheetdeactivate                     1081
#define dispid_application_ontime                                624
#define dispid_application_onundo                                770
#define dispid_application_onwindow                              623
#define dispid_application_operatingsystem                       375
#define dispid_application_organizationname                      376
#define dispid_application_path                                  291
#define dispid_application_pathseparator                         377
#define dispid_application_previousselections                    378
#define dispid_application_pivottableselection                   1205
#define dispid_application_promptforsummaryinfo                  1062
#define dispid_application_recordmacro                           773
#define dispid_application_recordrelaytive                       379
#define dispid_application_referencestyle                        380
#define dispid_application_registeredfunction                    775
#define dispid_application_registerxll                           30
#define dispid_application_repeat                                301
#define dispid_application_resettipwizard                        928
#define dispid_application_rollzoom                              1206
#define dispid_application_save                                  283
#define dispid_application_saveworkspace                         212
#define dispid_application_setdefaultchart                       219
#define dispid_application_sheetsinnewworkbook                   993
#define dispid_application_showcharttipnames                     1207
#define dispid_application_showcharttipvalues                    1208
#define dispid_application_standartfont                          924
#define dispid_application_standartfontsize                      925
#define dispid_application_startuppath                           385
#define dispid_application_statusbar                             386
#define dispid_application_templatespath                         381
#define dispid_application_showtooltips                          387
#define dispid_application_top                                   126
#define dispid_application_defaultsaveformat                     1209
#define dispid_application_transitionmenukey                     310
#define dispid_application_transitionmenukeyaction               311
#define dispid_application_transitionnavigkeys                   312
#define dispid_application_undo                                  303
#define dispid_application_usableheight                          389
#define dispid_application_usablewidth                           390
#define dispid_application_username                              391
#define dispid_application_value                                 6
#define dispid_application_vbe                                   1211
#define dispid_application_volatile                              788
#define dispid_application__wait                                 393
#define dispid_application_width                                 122
#define dispid_application_windowsforpens                        395
#define dispid_application_uilanguage                            2
#define dispid_application_defaultsheetdirection                 229
#define dispid_application_cursormovement                        232
#define dispid_application_controlcharacters                     233
#define dispid_application__wsfunction                           169
#define dispid_application_displayinfowindow                     1213
#define dispid_application_wait                                  1770
#define dispid_application_extendlist                            1793
#define dispid_application_oledberror                            1794
#define dispid_application_get_phonetic                          1795
#define dispid_application_comaddins                             1796
#define dispid_application_defaultweboptions                     1797
#define dispid_application_productcode                           1798
#define dispid_application_uselibrarypath                        1799
#define dispid_application_autopersententry                      1800
#define dispid_application_languagesettings                      1801
#define dispid_application_dummy101                              1802
#define dispid_application_dummy12                               1803
#define dispid_application_answerwizard                          1804
#define dispid_application_calculatefull                         1805
#define dispid_application_findfile                              1771
#define dispid_application_calculationversion                    1806
#define dispid_application_showwindowsintaskbar                  1807
#define dispid_application_featureinstall                        1808
#define dispid_application_ready                                 1932
#define dispid_application_dummy13                               1933
#define dispid_application_findformat                            1934
#define dispid_application_replaceformat                         1935
#define dispid_application_usedobject                            1936
#define dispid_application_calculationstate                      1937
#define dispid_application_calculationinterruptkey               1938
#define dispid_application_watches                               1939
#define dispid_application_displayfunctiontooltips               1940
#define dispid_application_automationsecurity                    1941
#define dispid_application_filedialog                            1942
#define dispid_application_dummy14                               1944
#define dispid_application_calculatefullrebuild                  1945
#define dispid_application_displaypasteoption                    1946
#define dispid_application_displayinsertoption                   1947
#define dispid_application_generategetpivotdata                  1948
#define dispid_application_autorecover                           1949
#define dispid_application_hwnd                                  1950
#define dispid_application_hinstance                             1951
#define dispid_application_checkabort                            1952
#define dispid_application_errorcheckingoptions                  1954
#define dispid_application_autoformatasyoutypereplacehyperlinks  1954
#define dispid_application_smarttagrecognizers                   1955
#define dispid_application_newworkbook                           1956
#define dispid_application_spellingoptions                       1957
#define dispid_application_speech                                1958
#define dispid_application_mappapersize                          1959
#define dispid_application_showstartupdialog                     1960
#define dispid_application_decimalseparator                      1809
#define dispid_application_thousandsseparator                    1810
#define dispid_application_usesystemseparator                    1961
#define dispid_application_thiscell                              1962
#define dispid_application_rtd                                   1963
#define dispid_application_displaydocumentactiontaskpan          0x000008cb
#define dispid_application_displayxmlsourcepane                  0x000008cc
#define dispid_application_arbitraryxmlsupportavailable          0x000008ce
#define dispid_application_support                               0x000008cf

/*IFont*/
#define dispid_font_application                                  1
#define dispid_font_creator                                      2
#define dispid_font_parent                                       3
#define dispid_font_background                                   3
#define dispid_font_bold                                         4
#define dispid_font_color                                        5
#define dispid_font_colorindex                                   6
#define dispid_font_fontstyle                                    7
#define dispid_font_italic                                       8
#define dispid_font_name                                         9
#define dispid_font_outlinefont                                  10
#define dispid_font_shadow                                       11
#define dispid_font_size                                         12
#define dispid_font_strikethrough                                13
#define dispid_font_subscript                                    14
#define dispid_font_superscript                                  15
#define dispid_font_underline                                    16

/*IInterior*/
#define dispid_interior_application                              1
#define dispid_interior_creator                                  2
#define dispid_interior_parent                                   3
#define dispid_interior_color                                    4
#define dispid_interior_colorindex                               5
#define dispid_interior_invertifnegative                         6
#define dispid_interior_pattern                                  7
#define dispid_interior_patterncolor                             8
#define dispid_interior_patterncolorindex                        9

/*IBorders*/
#define dispid_borders_application                               1
#define dispid_borders_creator                                   2
#define dispid_borders_parent                                    3
#define dispid_borders_color                                     4
#define dispid_borders_colorindex                                5
#define dispid_borders_count                                     6
#define dispid_borders_item                                      7
#define dispid_borders_linestyle                                 8
#define dispid_borders_getenumerator                             9
#define dispid_borders_value                                     10
#define dispid_borders_weight                                    11
#define dispid_borders__default                                  12

/*IBorder*/
#define dispid_border_application                                1
#define dispid_border_creator                                    2
#define dispid_border_parent                                     3
#define dispid_border_color                                      4
#define dispid_border_colorindex                                 5
#define dispid_border_linestyle                                  6
#define dispid_border_weight                                     7

/*IPageSetup*/
#define dispid_pagesetup_application                             1
#define dispid_pagesetup_creator                                 2
#define dispid_pagesetup_parent                                  3
#define dispid_pagesetup_blackandwhite                           4
#define dispid_pagesetup_bottommargin                            5
#define dispid_pagesetup_centerfooter                            6
#define dispid_pagesetup_centerheader                            7
#define dispid_pagesetup_centerhorizontall                       8
#define dispid_pagesetup_centervertically                        9
#define dispid_pagesetup_chartsize                               10
#define dispid_pagesetup_draft                                   11
#define dispid_pagesetup_firstpagenumber                         12
#define dispid_pagesetup_fittopagestall                          13
#define dispid_pagesetup_fittopageswide                          14
#define dispid_pagesetup_footermargin                            15
#define dispid_pagesetup_headermargin                            16
#define dispid_pagesetup_leftfooter                              17
#define dispid_pagesetup_leftheader                              18
#define dispid_pagesetup_leftmargin                              19
#define dispid_pagesetup_order                                   20
#define dispid_pagesetup_orientation                             21
#define dispid_pagesetup_papersize                               22
#define dispid_pagesetup_printarea                               23
#define dispid_pagesetup_printgridlines                          24
#define dispid_pagesetup_printheadings                           25
#define dispid_pagesetup_printnotes                              26
#define dispid_pagesetup_printquality                            27
#define dispid_pagesetup_printtitlecolumns                       28
#define dispid_pagesetup_printtitlerows                          29
#define dispid_pagesetup_rightfooter                             30
#define dispid_pagesetup_rightheader                             31
#define dispid_pagesetup_rightmargin                             32
#define dispid_pagesetup_topmargin                               33
#define dispid_pagesetup_zoom                                    34
#define dispid_pagesetup_printcomments                           35
#define dispid_pagesetup_printerrors                             36
#define dispid_pagesetup_centerheaderpicture                     37
#define dispid_pagesetup_centerfooterpicture                     38
#define dispid_pagesetup_leftheaderpicture                       39
#define dispid_pagesetup_leftfooterpicture                       40
#define dispid_pagesetup_rightheaderpicture                      41
#define dispid_pagesetup_rightfooterpicture                      42

/*Names*/
#define dispid_names_application                                 1
#define dispid_names_creator                                     2
#define dispid_names_parent                                      3
#define dispid_names_add                                         4
#define dispid_names_item                                        5
#define dispid_names__default                                    6
#define dispid_names_count                                       7
#define dispid_names_getenumerator                               8

/*IRange*/
#define dispid_range_application                                 1
#define dispid_range_creator                                     2
#define dispid_range_parent                                      3
#define dispid_range_activate                                    4
#define dispid_range_addindent                                   5
#define dispid_range_address                                     6
#define dispid_range_addresslocal                                7
#define dispid_range_advancedfilter                              8
#define dispid_range_applynames                                  9
#define dispid_range_applyoutlinestyles                          10
#define dispid_range_areas                                       11
#define dispid_range_autocomplete                                12
#define dispid_range_autofill                                    13
#define dispid_range_autofilter                                  14
#define dispid_range_autofit                                     15
#define dispid_range_autoformat                                  16
#define dispid_range_autooutline                                 17
#define dispid_range_borderaround                                18
#define dispid_range_borders                                     19
#define dispid_range_calculate                                   20
#define dispid_range_cells                                       21
#define dispid_range_characters                                  22
#define dispid_range_checkspelling                               23
#define dispid_range_clear                                       24
#define dispid_range_clearcontents                               25
#define dispid_range_clearformats                                26
#define dispid_range_clearnotes                                  27
#define dispid_range_clearoutline                                28
#define dispid_range_column                                      29
#define dispid_range_columndifferences                           30
#define dispid_range_columns                                     31
#define dispid_range_columnwidth                                 32
#define dispid_range_consolidate                                 33
#define dispid_range_copy                                        34
#define dispid_range_copyfromrecordset                           35
#define dispid_range_copypicture                                 36
#define dispid_range_count                                       37
#define dispid_range_createnames                                 38
#define dispid_range_createpublisher                             39
#define dispid_range_currentarray                                40
#define dispid_range_currentregion                               41
#define dispid_range_cut                                         42
#define dispid_range_dataseries                                  43
#define dispid_range__default                                    0
#define dispid_range_delete                                      44
#define dispid_range_dependents                                  45
#define dispid_range_dialogbox1                                  46
#define dispid_range_directdependents                            47
#define dispid_range_editionoptions                              48
#define dispid_range_end                                         49
#define dispid_range_entirecolumn                                50
#define dispid_range_entirerow                                   51
#define dispid_range_filldown                                    52
#define dispid_range_fillleft                                    53
#define dispid_range_fillright                                   54
#define dispid_range_fillup                                      55
#define dispid_range_find                                        56
#define dispid_range_findnext                                    57
#define dispid_range_findprevious                                58
#define dispid_range_font                                        59
#define dispid_range_formula                                     60
#define dispid_range_formulaarray                                61
#define dispid_range_formulalabel                                62
#define dispid_range_formulahidden                               63
#define dispid_range_formulalocal                                64
#define dispid_range_formular1c1                                 65
#define dispid_range_formular1c1local                            66
#define dispid_range_functionwizard                              67
#define dispid_range_goalSeek                                    68
#define dispid_range_group                                       69
#define dispid_range_hasarray                                    70
#define dispid_range_hasformula                                  71
#define dispid_range_height                                      72
#define dispid_range_hidden                                      73
#define dispid_range_horizontalalignment                         74
#define dispid_range_indentlevel                                 75
#define dispid_range_insertindent                                76
#define dispid_range_insert                                      77
#define dispid_range_interior                                    78
#define dispid_range_item                                        79
#define dispid_range_justify                                     80
#define dispid_range_left                                        81
#define dispid_range_listheaderrows                              82
#define dispid_range_listnames                                   83
#define dispid_range_locationintable                             84
#define dispid_range_locked                                      85
#define dispid_range_merge                                       86
#define dispid_range_unmerge                                     87
#define dispid_range_mergearea                                   88
#define dispid_range_mergecells                                  89
#define dispid_range_name                                        90
#define dispid_range_navigatearrow                               91
#define dispid_range__newenum                                    92
#define dispid_range_next                                        93
#define dispid_range_notetext                                    94
#define dispid_range_numberformat                                95
#define dispid_range_numberformatlocal                           96
#define dispid_range_offset                                      97
#define dispid_range_orientation                                 98
#define dispid_range_outlinelevel                                99
#define dispid_range_pagebreak                                   100
#define dispid_range_parse                                       101
#define dispid_range__pastespecial                               102
#define dispid_range_pivotfield                                  103
#define dispid_range_pivotitem                                   104
#define dispid_range_pivottable                                  105
#define dispid_range_precedents                                  106
#define dispid_range_prefixcharacter                             107
#define dispid_range_previous                                    108
#define dispid_range__printout                                   109
#define dispid_range_printpreview                                110
#define dispid_range_querytable                                  111
#define dispid_range_range                                       112
#define dispid_range_removesubtotal                              113
#define dispid_range_replace                                     114
#define dispid_range_resize                                      115
#define dispid_range_row                                         116
#define dispid_range_rowdifferences                              117
#define dispid_range_rowheight                                   118
#define dispid_range_rows                                        119
#define dispid_range_run                                         120
#define dispid_range_select                                      121
#define dispid_range_show                                        122
#define dispid_range_showdependents                              123
#define dispid_range_showdetail                                  124
#define dispid_range_showerrors                                  125
#define dispid_range_showprecedents                              126
#define dispid_range_shrinktofit                                 127
#define dispid_range_sort                                        128
#define dispid_range_sortspecial                                 129
#define dispid_range_soundnote                                   130
#define dispid_range_specialcells                                131
#define dispid_range_style                                       132
#define dispid_range_subscribeto                                 133
#define dispid_range_subtotal                                    134
#define dispid_range_summary                                     135
#define dispid_range_table                                       136
#define dispid_range_text                                        137
#define dispid_range_texttocolumns                               138
#define dispid_range_top                                         139
#define dispid_range_ungroup                                     140
#define dispid_range_usestandardheight                           141
#define dispid_range_usestandardwidth                            142
#define dispid_range_validation                                  143
#define dispid_range_value                                       144
#define dispid_range_value2                                      145
#define dispid_range_verticalalignment                           146
#define dispid_range_width                                       147
#define dispid_range_worksheet                                   148
#define dispid_range_wraptext                                    150
#define dispid_range_addcomment                                  151
#define dispid_range_comment                                     152
#define dispid_range_clearcomments                               153
#define dispid_range_phonetic                                    154
#define dispid_range_formatconditions                            155
#define dispid_range_readingorder                                156
#define dispid_range_hyperlinks                                  157
#define dispid_range_phonetics                                   158
#define dispid_range_setphonetic                                 159
#define dispid_range_id                                          160
#define dispid_range_printout                                    161
#define dispid_range_pivotcell                                   162
#define dispid_range_dirty                                       163
#define dispid_range_errors                                      164
#define dispid_range_smarttags                                   165
#define dispid_range_speak                                       166
#define dispid_range_pastespecial                                167
#define dispid_range_allowedit                                   168
#define dispid_range_listobject                                  169
#define dispid_range_xpath                                       170

/*ISheets*/
#define dispid_sheets_application                                148
#define dispid_sheets_creator                                    149
#define dispid_sheets_parent                                     150
#define dispid_sheets_add                                        181
#define dispid_sheets_copy                                       551
#define dispid_sheets_count                                      118
#define dispid_sheets_delete                                     117
#define dispid_sheets_fillacrosssheets                           469
#define dispid_sheets_item                                       170
#define dispid_sheets_move                                       637
#define dispid_sheets__newenum                                   -4
#define dispid_sheets__printout                                  905
#define dispid_sheets_printpreview                               281
#define dispid_sheets_select                                     235
#define dispid_sheets_hpagebreaks                                1418
#define dispid_sheets_vpagebreaks                                1419
#define dispid_sheets_visible                                    558
#define dispid_sheets__default                                   0
#define dispid_sheets_printout                                   1772
