
/*
 * Constants for dispid`s
 *
 * Copyright (C) 2008 Sinitsin Ivan (Etersoft) <ivan@etersoft.ru>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

/*ExcelApplication*/
#define dispid_application_usercontrol                           1210
#define dispid_application_displayalerts                         343
#define dispid_application_windowstate                           396
#define dispid_application_visible                               558
#define dispid_application_workbooks                             572
#define dispid_application_sheets                                485
#define dispid_application_worksheets                            494
#define dispid_application_cells                                 238
#define dispid_application_activesheet                           307
#define dispid_application_version                               392
#define dispid_application_convertformula                        325
#define dispid_application_quit                                  302
#define dispid_application_activecell                            305
#define dispid_application_application                           148
#define dispid_application_enableevents                          1212
#define dispid_application_screenupdating                        382
#define dispid_application_caption                               139
#define dispid_application_activeworkbook                        308
#define dispid_application_range                                 197
#define dispid_application_columns                               241
#define dispid_application_rows                                  258
#define dispid_application_selection                             147
#define dispid_application_creator                               149
#define dispid_application_parent                                150
#define dispid_application_activechart                           183
#define dispid_application_activedialog                          815
#define dispid_application_activemenubar                         758
#define dispid_application_activeprinter                         306
#define dispid_application_activewindow                          759
#define dispid_application_addins                                549
#define dispid_application_assistant                             1438
#define dispid_application_calculate                             279
#define dispid_application_charts                                121
#define dispid_application_commandbars                           1439
#define dispid_application_ddeappreturncode                      332
#define dispid_application_ddeexecute                            333
#define dispid_application_ddeinitiate                           334
#define dispid_application_ddepoke                               335
#define dispid_application_dderequest                            336
#define dispid_application_ddeterminate                          337
#define dispid_application_dialogsheets                          764
#define dispid_application_evaluate                              1
#define dispid_application__evaluate                             -5
#define dispid_application_evaluateexcel4macro                   350
#define dispid_application_intersect                             766
#define dispid_application_menubars                              589
#define dispid_application_modules                               582
#define dispid_application_names                                 442
#define dispid_application_run                                   259
#define dispid_application__run2                                 806
#define dispid_application_sendkeys                              383
#define dispid_application_shortcutmenus                         776
#define dispid_application_thisworkbook                          778
#define dispid_application_toolbars                              552
#define dispid_application_union                                 779
#define dispid_application_windows                               430
#define dispid_application_worksheetfunction                     1440
#define dispid_application_excel4intlmacrosheets                 581
#define dispid_application_excel4macrosheets                     579
#define dispid_application_activatemicrosoftapp                  1095
#define dispid_application_addchartautoformat                    216
#define dispid_application_addcustomlist                         780
#define dispid_application_alertbeforeoverwriting                930
#define dispid_application_altstartuppath                        313
#define dispid_application_asktoupdatelinks                      992
#define dispid_application_enableanimation                       1180
#define dispid_application_autocorrect                           1145
#define dispid_application_build                                 314
#define dispid_application_calculatebeforesave                   315
#define dispid_application_calculation                           316
#define dispid_application_caller                                317
#define dispid_application_canplaysounds                         318
#define dispid_application_canrecordsounds                       319
#define dispid_application_celldraganddrop                       320
#define dispid_application_centimeterstopoints                   1086
#define dispid_application_checkspelling                         505
#define dispid_application_clipboardformats                      321
#define dispid_application_displayclipboardwindow                322
#define dispid_application_colorbuttons                          365
#define dispid_application_commandunderlines                     323
#define dispid_application_constrainnumeric                      324
#define dispid_application_copyobjectswithcells                  991
#define dispid_application_cursor                                1161
#define dispid_application_customlistcount                       787
#define dispid_application_cutcopymode                           330
#define dispid_application_dataentrymode                         331
#define dispid_application_dummy1                                1782
#define dispid_application_dummy2                                1783
#define dispid_application_dummy3                                1784
#define dispid_application_dummy4                                1785
#define dispid_application_dummy5                                1786
#define dispid_application_dummy6                                1787
#define dispid_application_dummy7                                1788
#define dispid_application_dummy8                                1789
#define dispid_application_dummy9                                1790
#define dispid_application_dummy10                               1791
#define dispid_application_dummy11                               1792
#define dispid_application__default                              0
#define dispid_application_defaultfilepath                       1038
#define dispid_application_deletechartautoformat                 217
#define dispid_application_deletecustomlist                      783
#define dispid_application_dialogs                               761
#define dispid_application_displayformulabar                     344
#define dispid_application_displayfullscreen                     1061
#define dispid_application_displaynoteindicator                  345
#define dispid_application_displaycommentindicator               1196
#define dispid_application_displayexcel4menus                    927
#define dispid_application_displayrecentfiles                    926
#define dispid_application_displayscrollbars                     346
#define dispid_application_displaystatusbar                      347
#define dispid_application_doubleclick                           349
#define dispid_application_editdirectlyincell                    929
#define dispid_application_enableautocomplete                    1179
#define dispid_application_enablecancelkey                       1096
#define dispid_application_enablesound                           1197
#define dispid_application_enabletipwizard                       1064
#define dispid_application_fileconverters                        931
#define dispid_application_filesearch                            1200
#define dispid_application_filefind                              1201
#define dispid_application__findfile                             1068
#define dispid_application_fixeddecimal                          351
#define dispid_application_fixeddecimalplaces                    352
#define dispid_application_getcustomlistcontents                 786
#define dispid_application_getcustomlistnum                      785
#define dispid_application_getopenfilename                       1075
#define dispid_application_getsaveasfilename                     1076
#define dispid_application_goto                                  475
#define dispid_application_height                                123
#define dispid_application_help                                  354
#define dispid_application_ignoreremoterequests                  356
#define dispid_application_inchestopoints                        1087
#define dispid_application_inputbox                              357
#define dispid_application_interactive                           361
#define dispid_application_international                         362
#define dispid_application_iteration                             363
#define dispid_application_largebuttons                          364
#define dispid_application_left                                  127
#define dispid_application_librarypath                           366
#define dispid_application_macrooption                           1135
#define dispid_application_maillogoff                            945
#define dispid_application_maillogon                             943
#define dispid_application_mailsession                           942
#define dispid_application_mailsystem                            971
#define dispid_application_mathcoprocessoravailable              367
#define dispid_application_maxchange                             368
#define dispid_application_maxiterations                         369
#define dispid_application_memoryfree                            370
#define dispid_application_memorytotal                           371
#define dispid_application_memoryused                            373882
#define dispid_application_mouseavailable                        373
#define dispid_application_moveafterreturn                       374
#define dispid_application_moveafterreturndirection              1144
#define dispid_application_recentfiles                           1202
#define dispid_application_name                                  110
#define dispid_application_nextletter                            972
#define dispid_application_networktemplatespath                  388
#define dispid_application_odbcerrors                            1203
#define dispid_application_odbctimeout                           1204
#define dispid_application_oncalculate                           625
#define dispid_application_ondata                                629
#define dispid_application_ondoubleclick                         628
#define dispid_application_onentry                               627
#define dispid_application_onkey                                 626
#define dispid_application_onrepeat                              769
#define dispid_application_onsheetactivate                       1031
#define dispid_application_onsheetdeactivate                     1081
#define dispid_application_ontime                                624
#define dispid_application_onundo                                770
#define dispid_application_onwindow                              623
#define dispid_application_operatingsystem                       375
#define dispid_application_organizationname                      376
#define dispid_application_path                                  291
#define dispid_application_pathseparator                         377
#define dispid_application_previousselections                    378
#define dispid_application_pivottableselection                   1205
#define dispid_application_promptforsummaryinfo                  1062
#define dispid_application_recordmacro                           773
#define dispid_application_recordrelaytive                       379
#define dispid_application_referencestyle                        380
#define dispid_application_registeredfunction                    775
#define dispid_application_registerxll                           30
#define dispid_application_repeat                                301
#define dispid_application_resettipwizard                        928
#define dispid_application_rollzoom                              1206
#define dispid_application_save                                  283
#define dispid_application_saveworkspace                         212
#define dispid_application_setdefaultchart                       219
#define dispid_application_sheetsinnewworkbook                   993
#define dispid_application_showcharttipnames                     1207
#define dispid_application_showcharttipvalues                    1208
#define dispid_application_standartfont                          924
#define dispid_application_standartfontsize                      925
#define dispid_application_startuppath                           385
#define dispid_application_statusbar                             386
#define dispid_application_templatespath                         381
#define dispid_application_showtooltips                          387
#define dispid_application_top                                   126
#define dispid_application_defaultsaveformat                     1209
#define dispid_application_transitionmenukey                     310
#define dispid_application_transitionmenukeyaction               311
#define dispid_application_transitionnavigkeys                   312
#define dispid_application_undo                                  303
#define dispid_application_usableheight                          389
#define dispid_application_usablewidth                           390
#define dispid_application_username                              391
#define dispid_application_value                                 6
#define dispid_application_vbe                                   1211
#define dispid_application_volatile                              788
#define dispid_application__wait                                 393
#define dispid_application_width                                 122
#define dispid_application_windowsforpens                        395
#define dispid_application_uilanguage                            2
#define dispid_application_defaultsheetdirection                 229
#define dispid_application_cursormovement                        232
#define dispid_application_controlcharacters                     233
#define dispid_application__wsfunction                           169
#define dispid_application_displayinfowindow                     1213
#define dispid_application_wait                                  1770
#define dispid_application_extendlist                            1793
#define dispid_application_oledberror                            1794
#define dispid_application_get_phonetic                          1795
#define dispid_application_comaddins                             1796
#define dispid_application_defaultweboptions                     1797
#define dispid_application_productcode                           1798
#define dispid_application_uselibrarypath                        1799
#define dispid_application_autopersententry                      1800
#define dispid_application_languagesettings                      1801
#define dispid_application_dummy101                              1802
#define dispid_application_dummy12                               1803
#define dispid_application_answerwizard                          1804
#define dispid_application_calculatefull                         1805
#define dispid_application_findfile                              1771
#define dispid_application_calculationversion                    1806
#define dispid_application_showwindowsintaskbar                  1807
#define dispid_application_featureinstall                        1808
#define dispid_application_ready                                 1932
#define dispid_application_dummy13                               1933
#define dispid_application_findformat                            1934
#define dispid_application_replaceformat                         1935
#define dispid_application_usedobject                            1936
#define dispid_application_calculationstate                      1937
#define dispid_application_calculationinterruptkey               1938
#define dispid_application_watches                               1939
#define dispid_application_displayfunctiontooltips               1940
#define dispid_application_automationsecurity                    1941
#define dispid_application_filedialog                            1942
#define dispid_application_dummy14                               1944
#define dispid_application_calculatefullrebuild                  1945
#define dispid_application_displaypasteoption                    1946
#define dispid_application_displayinsertoption                   1947
#define dispid_application_generategetpivotdata                  1948
#define dispid_application_autorecover                           1949
#define dispid_application_hwnd                                  1950
#define dispid_application_hinstance                             1951
#define dispid_application_checkabort                            1952
#define dispid_application_errorcheckingoptions                  1954
#define dispid_application_autoformatasyoutypereplacehyperlinks  1954
#define dispid_application_smarttagrecognizers                   1955
#define dispid_application_newworkbook                           1956
#define dispid_application_spellingoptions                       1957
#define dispid_application_speech                                1958
#define dispid_application_mappapersize                          1959
#define dispid_application_showstartupdialog                     1960
#define dispid_application_decimalseparator                      1809
#define dispid_application_thousandsseparator                    1810
#define dispid_application_usesystemseparator                    1961
#define dispid_application_thiscell                              1962
#define dispid_application_rtd                                   1963
#define dispid_application_displaydocumentactiontaskpan          0x000008cb
#define dispid_application_displayxmlsourcepane                  0x000008cc
#define dispid_application_arbitraryxmlsupportavailable          0x000008ce
#define dispid_application_support                               0x000008cf

/*IFont*/
#define dispid_font_application                                  1
#define dispid_font_creator                                      2
#define dispid_font_parent                                       3
#define dispid_font_background                                   3
#define dispid_font_bold                                         4
#define dispid_font_color                                        5
#define dispid_font_colorindex                                   6
#define dispid_font_fontstyle                                    7
#define dispid_font_italic                                       8
#define dispid_font_name                                         9
#define dispid_font_outlinefont                                  10
#define dispid_font_shadow                                       11
#define dispid_font_size                                         12
#define dispid_font_strikethrough                                13
#define dispid_font_subscript                                    14
#define dispid_font_superscript                                  15
#define dispid_font_underline                                    16

/*IInterior*/
#define dispid_interior_application                              1
#define dispid_interior_creator                                  2
#define dispid_interior_parent                                   3
#define dispid_interior_color                                    4
#define dispid_interior_colorindex                               5
#define dispid_interior_invertifnegative                         6
#define dispid_interior_pattern                                  7
#define dispid_interior_patterncolor                             8
#define dispid_interior_patterncolorindex                        9

/*IBorders*/
#define dispid_borders_application                               1
#define dispid_borders_creator                                   2
#define dispid_borders_parent                                    3
#define dispid_borders_color                                     4
#define dispid_borders_colorindex                                5
#define dispid_borders_count                                     6
#define dispid_borders_item                                      7
#define dispid_borders_linestyle                                 8
#define dispid_borders_getenumerator                             9
#define dispid_borders_value                                     10
#define dispid_borders_weight                                    11
#define dispid_borders__default                                  0

/*IBorder*/
#define dispid_border_application                                1
#define dispid_border_creator                                    2
#define dispid_border_parent                                     3
#define dispid_border_color                                      4
#define dispid_border_colorindex                                 5
#define dispid_border_linestyle                                  6
#define dispid_border_weight                                     7

/*IPageSetup*/
#define dispid_pagesetup_application                             1
#define dispid_pagesetup_creator                                 2
#define dispid_pagesetup_parent                                  3
#define dispid_pagesetup_blackandwhite                           4
#define dispid_pagesetup_bottommargin                            5
#define dispid_pagesetup_centerfooter                            6
#define dispid_pagesetup_centerheader                            7
#define dispid_pagesetup_centerhorizontall                       8
#define dispid_pagesetup_centervertically                        9
#define dispid_pagesetup_chartsize                               10
#define dispid_pagesetup_draft                                   11
#define dispid_pagesetup_firstpagenumber                         12
#define dispid_pagesetup_fittopagestall                          13
#define dispid_pagesetup_fittopageswide                          14
#define dispid_pagesetup_footermargin                            15
#define dispid_pagesetup_headermargin                            16
#define dispid_pagesetup_leftfooter                              17
#define dispid_pagesetup_leftheader                              18
#define dispid_pagesetup_leftmargin                              19
#define dispid_pagesetup_order                                   20
#define dispid_pagesetup_orientation                             21
#define dispid_pagesetup_papersize                               22
#define dispid_pagesetup_printarea                               23
#define dispid_pagesetup_printgridlines                          24
#define dispid_pagesetup_printheadings                           25
#define dispid_pagesetup_printnotes                              26
#define dispid_pagesetup_printquality                            27
#define dispid_pagesetup_printtitlecolumns                       28
#define dispid_pagesetup_printtitlerows                          29
#define dispid_pagesetup_rightfooter                             30
#define dispid_pagesetup_rightheader                             31
#define dispid_pagesetup_rightmargin                             32
#define dispid_pagesetup_topmargin                               33
#define dispid_pagesetup_zoom                                    34
#define dispid_pagesetup_printcomments                           35
#define dispid_pagesetup_printerrors                             36
#define dispid_pagesetup_centerheaderpicture                     37
#define dispid_pagesetup_centerfooterpicture                     38
#define dispid_pagesetup_leftheaderpicture                       39
#define dispid_pagesetup_leftfooterpicture                       40
#define dispid_pagesetup_rightheaderpicture                      41
#define dispid_pagesetup_rightfooterpicture                      42

/*Names*/
#define dispid_names_application                                 1
#define dispid_names_creator                                     2
#define dispid_names_parent                                      3
#define dispid_names_add                                         4
#define dispid_names_item                                        5
#define dispid_names__default                                    0
#define dispid_names_count                                       7
#define dispid_names_getenumerator                               -4

/*IRange*/
#define dispid_range_application                                 148
#define dispid_range_creator                                     149
#define dispid_range_parent                                      150
#define dispid_range_activate                                    304
#define dispid_range_addindent                                   1063
#define dispid_range_address                                     236
#define dispid_range_addresslocal                                437
#define dispid_range_advancedfilter                              876
#define dispid_range_applynames                                  441
#define dispid_range_applyoutlinestyles                          448
#define dispid_range_areas                                       568
#define dispid_range_autocomplete                                1185
#define dispid_range_autofill                                    449
#define dispid_range_autofilter                                  793
#define dispid_range_autofit                                     237
#define dispid_range_autoformat                                  114
#define dispid_range_autooutline                                 1036
#define dispid_range_borderaround                                1067
#define dispid_range_borders                                     435
#define dispid_range_calculate                                   279
#define dispid_range_cells                                       238
#define dispid_range_characters                                  603
#define dispid_range_checkspelling                               505
#define dispid_range_clear                                       111
#define dispid_range_clearcontents                               113
#define dispid_range_clearformats                                112
#define dispid_range_clearnotes                                  239
#define dispid_range_clearoutline                                1037
#define dispid_range_column                                      240
#define dispid_range_columndifferences                           510
#define dispid_range_columns                                     241
#define dispid_range_columnwidth                                 242
#define dispid_range_consolidate                                 482
#define dispid_range_copy                                        551
#define dispid_range_copyfromrecordset                           1152
#define dispid_range_copypicture                                 213
#define dispid_range_count                                       118
#define dispid_range_createnames                                 457
#define dispid_range_createpublisher                             458
#define dispid_range_currentarray                                501
#define dispid_range_currentregion                               243
#define dispid_range_cut                                         565
#define dispid_range_dataseries                                  464
#define dispid_range__default                                    0
#define dispid_range_delete                                      117
#define dispid_range_dependents                                  543
#define dispid_range_dialogbox1                                  245
#define dispid_range_directdependents                            545
#define dispid_range_editionoptions                              546
#define dispid_range_end                                         1131
#define dispid_range_entirecolumn                                500
#define dispid_range_entirerow                                   246
#define dispid_range_filldown                                    247
#define dispid_range_fillleft                                    248
#define dispid_range_fillright                                   249
#define dispid_range_fillup                                      250
#define dispid_range_find                                        251
#define dispid_range_findnext                                    398
#define dispid_range_findprevious                                399
#define dispid_range_font                                        400
#define dispid_range_formula                                     146
#define dispid_range_formulaarray                                261
#define dispid_range_formulalabel                                586
#define dispid_range_formulahidden                               1380
#define dispid_range_formulalocal                                262
#define dispid_range_formular1c1                                 263
#define dispid_range_formular1c1local                            264
#define dispid_range_functionwizard                              265
#define dispid_range_goalSeek                                    571
#define dispid_range_group                                       472
#define dispid_range_hasarray                                    46
#define dispid_range_hasformula                                  266
#define dispid_range_height                                      267
#define dispid_range_hidden                                      123
#define dispid_range_horizontalalignment                         268
#define dispid_range_indentlevel                                 136
#define dispid_range_insertindent                                201
#define dispid_range_insert                                      1381
#define dispid_range_interior                                    252
#define dispid_range_item                                        129
#define dispid_range_justify                                     170
#define dispid_range_left                                        495
#define dispid_range_listheaderrows                              127
#define dispid_range_listnames                                   1187
#define dispid_range_locationintable                             253
#define dispid_range_locked                                      269
#define dispid_range_merge                                       564
#define dispid_range_unmerge                                     1384
#define dispid_range_mergearea                                   1385
#define dispid_range_mergecells                                  208
#define dispid_range_name                                        110
#define dispid_range_navigatearrow                               1032
#define dispid_range__newenum                                    -4
#define dispid_range_next                                        502
#define dispid_range_notetext                                    1127
#define dispid_range_numberformat                                193
#define dispid_range_numberformatlocal                           1097
#define dispid_range_offset                                      254
#define dispid_range_orientation                                 134
#define dispid_range_outlinelevel                                271
#define dispid_range_pagebreak                                   255
#define dispid_range_parse                                       477
#define dispid_range__pastespecial                               1027
#define dispid_range_pivotfield                                  731
#define dispid_range_pivotitem                                   740
#define dispid_range_pivottable                                  716
#define dispid_range_precedents                                  544
#define dispid_range_prefixcharacter                             504
#define dispid_range_previous                                    503
#define dispid_range__printout                                   905
#define dispid_range_printpreview                                281
#define dispid_range_querytable                                  1386
#define dispid_range_range                                       197
#define dispid_range_removesubtotal                              883
#define dispid_range_replace                                     226
#define dispid_range_resize                                      256
#define dispid_range_row                                         257
#define dispid_range_rowdifferences                              511
#define dispid_range_rowheight                                   272
#define dispid_range_rows                                        258
#define dispid_range_run                                         259
#define dispid_range_select                                      235
#define dispid_range_show                                        496
#define dispid_range_showdependents                              877
#define dispid_range_showdetail                                  585
#define dispid_range_showerrors                                  878
#define dispid_range_showprecedents                              879
#define dispid_range_shrinktofit                                 209
#define dispid_range_sort                                        880
#define dispid_range_sortspecial                                 881
#define dispid_range_soundnote                                   916
#define dispid_range_specialcells                                410
#define dispid_range_style                                       260
#define dispid_range_subscribeto                                 481
#define dispid_range_subtotal                                    882
#define dispid_range_summary                                     273
#define dispid_range_table                                       497
#define dispid_range_text                                        138
#define dispid_range_texttocolumns                               1040
#define dispid_range_top                                         126
#define dispid_range_ungroup                                     244
#define dispid_range_usestandardheight                           274
#define dispid_range_usestandardwidth                            275
#define dispid_range_validation                                  1387
#define dispid_range_value                                       6
#define dispid_range_value2                                      1388
#define dispid_range_verticalalignment                           137
#define dispid_range_width                                       122
#define dispid_range_worksheet                                   348
#define dispid_range_wraptext                                    276
#define dispid_range_addcomment                                  1389
#define dispid_range_comment                                     910
#define dispid_range_clearcomments                               1390
#define dispid_range_phonetic                                    1391
#define dispid_range_formatconditions                            1392
#define dispid_range_readingorder                                975
#define dispid_range_hyperlinks                                  1393
#define dispid_range_phonetics                                   1811
#define dispid_range_setphonetic                                 1812
#define dispid_range_id                                          1813
#define dispid_range_printout                                    1772
#define dispid_range_pivotcell                                   2013
#define dispid_range_dirty                                       2014
#define dispid_range_errors                                      2015
#define dispid_range_smarttags                                   2016
#define dispid_range_speak                                       2017
#define dispid_range_pastespecial                                1928
#define dispid_range_allowedit                                   2020
#define dispid_range_listobject                                  2021
#define dispid_range_xpath                                       2022

/*ISheets*/
#define dispid_sheets_application                                148
#define dispid_sheets_creator                                    149
#define dispid_sheets_parent                                     150
#define dispid_sheets_add                                        181
#define dispid_sheets_copy                                       551
#define dispid_sheets_count                                      118
#define dispid_sheets_delete                                     117
#define dispid_sheets_fillacrosssheets                           469
#define dispid_sheets_item                                       170
#define dispid_sheets_move                                       637
#define dispid_sheets__newenum                                   -4
#define dispid_sheets__printout                                  905
#define dispid_sheets_printpreview                               281
#define dispid_sheets_select                                     235
#define dispid_sheets_hpagebreaks                                1418
#define dispid_sheets_vpagebreaks                                1419
#define dispid_sheets_visible                                    558
#define dispid_sheets__default                                   0
#define dispid_sheets_printout                                   1772

/*IWorksheet*/
#define dispid_worksheet_application                             148
#define dispid_worksheet_creator                                 149
#define dispid_worksheet_parent                                  150
#define dispid_worksheet_activate                                304
#define dispid_worksheet_copy                                    551
#define dispid_worksheet_delete                                  117
#define dispid_worksheet_codename                                1373
#define dispid_worksheet__codename                               -2147418112
#define dispid_worksheet_index                                   486
#define dispid_worksheet_move                                    637
#define dispid_worksheet_name                                    110
#define dispid_worksheet_next                                    502
#define dispid_worksheet_ondoubleclick                           628
#define dispid_worksheet_onsheetactivate                         1031
#define dispid_worksheet_onsheetdeactivate                       1081
#define dispid_worksheet_pagesetup                               998
#define dispid_worksheet_previous                                503
#define dispid_worksheet__printout                               905
#define dispid_worksheet_printpreview                            281
#define dispid_worksheet__protect                                282
#define dispid_worksheet_protectcontents                         292
#define dispid_worksheet_protectdrawingobjects                   293
#define dispid_worksheet_protectionmode                          1159
#define dispid_worksheet_protectscenarios                        294
#define dispid_worksheet__saveas                                 284
#define dispid_worksheet_select                                  235
#define dispid_worksheet_unprotect                               285
#define dispid_worksheet_visible                                 558
#define dispid_worksheet_shapes                                  1377
#define dispid_worksheet_transitionexpeval                       401
#define dispid_worksheet_arcs                                    760
#define dispid_worksheet_autofiltermode                          792
#define dispid_worksheet_setbackgroundpicture                    1188
#define dispid_worksheet_buttons                                 557
#define dispid_worksheet_calculate                               279
#define dispid_worksheet_enablecalculation                       1424
#define dispid_worksheet_cells                                   238
#define dispid_worksheet_chartobjects                            1060
#define dispid_worksheet_checkboxes                              824
#define dispid_worksheet_checkspelling                           505
#define dispid_worksheet_circularreference                       1069
#define dispid_worksheet_cleararrows                             970
#define dispid_worksheet_columns                                 241
#define dispid_worksheet_consolidationfunction                   789
#define dispid_worksheet_consolidationoptions                    790
#define dispid_worksheet_consolidationsources                    791
#define dispid_worksheet_displayautomaticpagebreaks              643
#define dispid_worksheet_drawings                                772
#define dispid_worksheet_drawingobjects                          88
#define dispid_worksheet_dropdowns                               836
#define dispid_worksheet_enableautofilter                        1156
#define dispid_worksheet_enableselection                         1425
#define dispid_worksheet_enableoutlining                         1157
#define dispid_worksheet_enablepivottable                        1158
#define dispid_worksheet_evaluate                                1
#define dispid_worksheet__evaluate                               -5
#define dispid_worksheet_filtermode                              800
#define dispid_worksheet_resetallpagebreaks                      1426
#define dispid_worksheet_groupboxes                              834
#define dispid_worksheet_groupobjects                            1113
#define dispid_worksheet_labels                                  841
#define dispid_worksheet_lines                                   767
#define dispid_worksheet_listboxes                               832
#define dispid_worksheet_names                                   442
#define dispid_worksheet_oleobjects                              799
#define dispid_worksheet_oncalculate                             625
#define dispid_worksheet_ondata                                  629
#define dispid_worksheet_onentry                                 627
#define dispid_worksheet_optionbuttons                           826
#define dispid_worksheet_outline                                 102
#define dispid_worksheet_ovals                                   801
#define dispid_worksheet_paste                                   211
#define dispid_worksheet__pastespecial                           1027
#define dispid_worksheet_pictures                                771
#define dispid_worksheet_pivottables                             690
#define dispid_worksheet_pivottablewizard                        684
#define dispid_worksheet_range                                   197
#define dispid_worksheet_rectangles                              774
#define dispid_worksheet_rows                                    258
#define dispid_worksheet_scenarios                               908
#define dispid_worksheet_scrollarea                              1433
#define dispid_worksheet_scrollbars                              830
#define dispid_worksheet_showalldata                             794
#define dispid_worksheet_showdataform                            409
#define dispid_worksheet_spinners                                838
#define dispid_worksheet_standardheight                          407
#define dispid_worksheet_standardwidth                           408
#define dispid_worksheet_textboxes                               777
#define dispid_worksheet_transitionformentry                     402
#define dispid_worksheet_type                                    108
#define dispid_worksheet_usedrange                               412
#define dispid_worksheet_hpagebreaks                             1418
#define dispid_worksheet_vpagebreaks                             1419
#define dispid_worksheet_querytables                             1434
#define dispid_worksheet_displaypagebreaks                       1435
#define dispid_worksheet_comments                                575
#define dispid_worksheet_hyperlinks                              1393
#define dispid_worksheet_clearcircles                            1436
#define dispid_worksheet_circleinvalid                           1437
#define dispid_worksheet__displayrighttoleft                     648
#define dispid_worksheet_autofilter                              793
#define dispid_worksheet_displayrighttoleft                      1774
#define dispid_worksheet_scripts                                 1816
#define dispid_worksheet_printout                                1772
#define dispid_worksheet__checkspelling                          1817
#define dispid_worksheet_tab                                     1041
#define dispid_worksheet_mailenvelope                            2021
#define dispid_worksheet_saveas                                  1925
#define dispid_worksheet_customproperties                        2030
#define dispid_worksheet_smarttags                               2016
#define dispid_worksheet_protection                              176
#define dispid_worksheet_pastespecial                            1928
#define dispid_worksheet_protect                                 2029
#define dispid_worksheet_listobjects                             6
#define dispid_worksheet_xmldataquery                            7
#define dispid_worksheet_xmlmapquery                             8

/*IWorkbooks*/
#define dispid_workbooks_application                             148
#define dispid_workbooks_creator                                 149
#define dispid_workbooks_parent                                  150
#define dispid_workbooks_Add                                     181
#define dispid_workbooks_Close                                   277
#define dispid_workbooks_Count                                   118
#define dispid_workbooks_Item                                    170
#define dispid_workbooks__NewEnum                                -4
#define dispid_workbooks__Open                                   682
#define dispid_workbooks___OpenText                              683
#define dispid_workbooks__Default                                0
#define dispid_workbooks__OpenText                               1773
#define dispid_workbooks_Open                                    1923
#define dispid_workbooks_OpenText                                1924
#define dispid_workbooks_OpenDatabase                            2067
#define dispid_workbooks_CheckOut                                2069
#define dispid_workbooks_CanCheckOut                             2070
#define dispid_workbooks__OpenXML                                2071
#define dispid_workbooks_OpenXML                                 2072

/*IWorkbook*/
#define dispid_workbook_application                              148
#define dispid_workbook_creator                                  149
#define dispid_workbook_parent                                   150
#define dispid_workbook_acceptlabelsinformulas                   1441
#define dispid_workbook_activate                                 304
#define dispid_workbook_activeChart                              183
#define dispid_workbook_activeSheet                              307
#define dispid_workbook_author                                   574
#define dispid_workbook_autoupdatefrequency                      1442
#define dispid_workbook_autoupdatesavechanges                    1443
#define dispid_workbook_changehistoryduration                    1444
#define dispid_workbook_builtindocumentproperties                1176
#define dispid_workbook_changefileaccess                         989
#define dispid_workbook_changelink                               802
#define dispid_workbook_charts                                   121
#define dispid_workbook_close                                    277
#define dispid_workbook_codename                                 1373
#define dispid_workbook__codename                                -2147418112
#define dispid_workbook_colors                                   286
#define dispid_workbook_commandbars                              1439
#define dispid_workbook_comments                                 575
#define dispid_workbook_conflictresolution                       1175
#define dispid_workbook_container                                1190
#define dispid_workbook_createbackup                             287
#define dispid_workbook_customdocumentproperties                 1177
#define dispid_workbook_date1904                                 403
#define dispid_workbook_deletenumberformat                       397
#define dispid_workbook_dialogsheets                             764
#define dispid_workbook_displaydrawingobjects                    404
#define dispid_workbook_exclusiveaccess                          1168
#define dispid_workbook_fileformat                               288
#define dispid_workbook_forwardmailer                            973
#define dispid_workbook_fullname                                 289
#define dispid_workbook_hasmailer                                976
#define dispid_workbook_haspassword                              290
#define dispid_workbook_hasroutingslip                           950
#define dispid_workbook_isaddin                                  1445
#define dispid_workbook_keywords                                 577
#define dispid_workbook_linkinfo                                 807
#define dispid_workbook_linksources                              808
#define dispid_workbook_mailer                                   976
#define dispid_workbook_mergeworkbook                            1446
#define dispid_workbook_modules                                  582
#define dispid_workbook_multiuserediting                         1169
#define dispid_workbook_name                                     110
#define dispid_workbook_names                                    442
#define dispid_workbook_newwindow                                280
#define dispid_workbook_onsave                                   1178
#define dispid_workbook_onsheetactivate                          1031
#define dispid_workbook_onsheetdeactivate                        1081
#define dispid_workbook_openlinks                                803
#define dispid_workbook_path                                     291
#define dispid_workbook_personalviewlistsettings                 1447
#define dispid_workbook_personalviewprintsettings                1448
#define dispid_workbook_pivotcaches                              1449
#define dispid_workbook_post                                     1166
#define dispid_workbook_precisionasdisplayed                     405
#define dispid_workbook__printout                                905
#define dispid_workbook_printpreview                             281
#define dispid_workbook__protect                                 282
#define dispid_workbook_protectsharing                           1450
#define dispid_workbook_protectstructure                         588
#define dispid_workbook_protectwindows                           295
#define dispid_workbook_readonly                                 296
#define dispid_workbook__readonlyrecommended                     297
#define dispid_workbook_refreshall                               1452
#define dispid_workbook_reply                                    977
#define dispid_workbook_replyall                                 978
#define dispid_workbook_removeuser                               1453
#define dispid_workbook_revisionnumber                           1172
#define dispid_workbook_route                                    946
#define dispid_workbook_routed                                   951
#define dispid_workbook_routingslip                              949
#define dispid_workbook_runautomacros                            634
#define dispid_workbook_save                                     283
#define dispid_workbook__saveas                                  284
#define dispid_workbook_savecopyas                               175
#define dispid_workbook_saved                                    298
#define dispid_workbook_savelinkvalues                           406
#define dispid_workbook_sendmail                                 947
#define dispid_workbook_sendmailer                               980
#define dispid_workbook_setLinkondata                            809
#define dispid_workbook_sheets                                   485
#define dispid_workbook_showconflicthistory                      1171
#define dispid_workbook_styles                                   493
#define dispid_workbook_subject                                  953
#define dispid_workbook_title                                    199
#define dispid_workbook_unprotect                                285
#define dispid_workbook_unprotectsharing                         1455
#define dispid_workbook_updatefromfile                           995
#define dispid_workbook_updatelink                               804
#define dispid_workbook_updateremotereferences                   411
#define dispid_workbook_usercontrol                              1210
#define dispid_workbook_userstatus                               1173
#define dispid_workbook_customviews                              1456
#define dispid_workbook_windows                                  430
#define dispid_workbook_worksheets                               494
#define dispid_workbook_writereserved                            299
#define dispid_workbook_writereservedby                          300
#define dispid_workbook_excel4intlmacrosheets                    581
#define dispid_workbook_excel4macrosheets                        579
#define dispid_workbook_templateremoveextdata                    1457
#define dispid_workbook_highlightchangesoptions                  1458
#define dispid_workbook_highlightchangesonScreen                 1461
#define dispid_workbook_keepchangehistory                        1462
#define dispid_workbook_listchangesonnewsheet                    1463
#define dispid_workbook_purgechangehistorynow                    1464
#define dispid_workbook_acceptallchanges                         1466
#define dispid_workbook_rejectallchanges                         1467
#define dispid_workbook_pivottablewizard                         684
#define dispid_workbook_resetcolors                              1468
#define dispid_workbook_vbproject                                1469
#define dispid_workbook_followhyperlink                          1470
#define dispid_workbook_addtofavorites                           1476
#define dispid_workbook_isinplace                                1769
#define dispid_workbook_printout                                 1772
#define dispid_workbook_webpagepreview                           1818
#define dispid_workbook_publishobjects                           1819
#define dispid_workbook_weboptions                               1820
#define dispid_workbook_reloadas                                 1821
#define dispid_workbook_htmlproject                              1823
#define dispid_workbook_envelopevisible                          1824
#define dispid_workbook_calculationVersion                       1806
#define dispid_workbook_dummy17                                  2044
#define dispid_workbook_sblt                                     1826
#define dispid_workbook_vbasigned                                1828
#define dispid_workbook_showpivottablefieldlist                  2046
#define dispid_workbook_updatelinks                              864
#define dispid_workbook_breaklink                                2047
#define dispid_workbook_dummy16                                  2048
#define dispid_workbook_saveas                                   1925
#define dispid_workbook_enableautorecover                        2049
#define dispid_workbook_removepersonalinformation                2050
#define dispid_workbook_fullnameurlencoded                       1927
#define dispid_workbook_checkin                                  2051
#define dispid_workbook_cancheckin                               2053
#define dispid_workbook_sendforreview                            2054
#define dispid_workbook_replywithchanges                         2057
#define dispid_workbook_endreview                                2058
#define dispid_workbook_password                                 429
#define dispid_workbook_writepassword                            1128
#define dispid_workbook_passwordencryptionprovider               2059
#define dispid_workbook_passwordencryptionalgorithm              2060
#define dispid_workbook_passwordencryptionkeylength              2061
#define dispid_workbook_setpasswordencryptionoptions             2062
#define dispid_workbook_passwordencryptionfileproperties         2063
#define dispid_workbook_readonlyrecommended                      2005
#define dispid_workbook_protect                                  2029
#define dispid_workbook_smarttagoptions                          2064
#define dispid_workbook_rechecksmarttags                         2065
#define dispid_workbook_permission                               2
#define dispid_workbook_sharedworkspace                          3
#define dispid_workbook_sync                                     4
#define dispid_workbook_sendfaxoverinternet                      5
#define dispid_workbook_xmlnamespaces                            6
#define dispid_workbook_xmlmaps                                  7
#define dispid_workbook_xmlimport                                8
#define dispid_workbook_smartdocument                            9
#define dispid_workbook_documentlibraryversions                  10
#define dispid_workbook_inactivelistbordervisible                11
#define dispid_workbook_displayinkcomments                       12
#define dispid_workbook_xmlimportxml                             13
#define dispid_workbook_saveAsxmldata                            14
#define dispid_workbook_toggleformsdesign                        15

/*Name*/
#define dispid_name_application                                 1
#define dispid_name_creator                                     2
#define dispid_name_parent                                      3
#define dispid_name__default                                    0
#define dispid_name_index                                       5
#define dispid_name_category                                    6
#define dispid_name_categorylocal                               7
#define dispid_name_delete                                      8
#define dispid_name_macrotype                                   9
#define dispid_name_name                                        10
#define dispid_name_refersto                                    11
#define dispid_name_shortcutkey                                 12
#define dispid_name_value                                       13
#define dispid_name_visible                                     14
#define dispid_name_namelocal                                   15
#define dispid_name_referstolocal                               16
#define dispid_name_referstor1c1                                17
#define dispid_name_referstor1c1local                           18
#define dispid_name_referstorange                               19

/*IOutline*/
#define dispid_outline_application                              148
#define dispid_outline_creator                                  149
#define dispid_outline_parent                                   150
#define dispid_outline_automaticstyles                          959
#define dispid_outline_showlevels                               960
#define dispid_outline_summarycolumn                            961
#define dispid_outline_summaryrow                               902

/*IWindows*/
#define dispid_windows_application                              148
#define dispid_windows_creator                                  149
#define dispid_windows_parent                                   150
#define dispid_windows_arrange                                  1
#define dispid_windows_count                                    2
#define dispid_windows_item                                     3
#define dispid_windows__newenum                                 4
#define dispid_windows__default                                 0


/*IWindow*/
#define dispid_window_application                              148
#define dispid_window_creator                                  149
#define dispid_window_parent                                   150
#define dispid_window_activate                                 1
#define dispid_window_activatenext                             2
#define dispid_window_activateprevious                         3
#define dispid_window_activecell                               4
#define dispid_window_activechart                              5
#define dispid_window_activepane                               6
#define dispid_window_activesheet                              7
#define dispid_window_caption                                  8
#define dispid_window_close                                    9
#define dispid_window_displayformulas                          10
#define dispid_window_displaygridlines                         11
#define dispid_window_displayheadings                          12
#define dispid_window_displayhorisontalscrollbar               13
#define dispid_window_displayoutline                           14
#define dispid_window__displayrighttoleft                      15
#define dispid_window_displayverticalscrollbar                 16
#define dispid_window_displayworkbooktabs                      17
#define dispid_window_displayzeros                             18
#define dispid_window_enableresize                             19
#define dispid_window_freezepanes                              20
#define dispid_window_gridlinecolor                            21
#define dispid_window_gridlinecolorindex                       22
#define dispid_window_height                                   23
#define dispid_window_index                                    24
#define dispid_window_largescroll                              25
#define dispid_window_left                                     26
#define dispid_window_newwindow                                27
#define dispid_window_onwindow                                 28
#define dispid_window_panes                                    29
#define dispid_window_printout                                 30
#define dispid_window_printpreview                             31
#define dispid_window_rangeselection                           32
#define dispid_window_scrollcolumn                             33
#define dispid_window_scrollrow                                34
#define dispid_window_scrollworkbooktabs                       35
#define dispid_window_selectedsheets                           36
#define dispid_window_selection                                37
#define dispid_window_smallscroll                              38
#define dispid_window_split                                    39
#define dispid_window_splitcolumn                              40
#define dispid_window_splithorisontal                          41
#define dispid_window_splitrow                                 42
#define dispid_window_splitvertical                            43
#define dispid_window_tabratio                                 44
#define dispid_window_top                                      45
#define dispid_window_type                                     46
#define dispid_window_usableheight                             47
#define dispid_window_usablewidth                              48
#define dispid_window_visible                                  49
#define dispid_window_visiblerange                             50
#define dispid_window_width                                    51
#define dispid_window_windownumber                             52
#define dispid_window_windowstate                              53
#define dispid_window_zoom                                     54
#define dispid_window_view                                     55
#define dispid_window_displayrighttoleft                       56
#define dispid_window_pointstoscreenpixelsx                    57
#define dispid_window_pointstoscreenpixelsy                    58
#define dispid_window_rangefrompoint                           59
#define dispid_window_scrollintoview                           60
